In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
import pickle

In [2]:
df = pd.read_csv('non_parametric.csv')

df.head()

,Unnamed: 0,Age,ASF,nWBV,eTIV,Gender_M,Educ_level_2.0,Educ_level_3.0,Educ_level_4.0,Educ_level_5.0,SES_level_2.0,SES_level_3.0,SES_level_4.0,SES_level_5.0,MMSE_Group_> 25,Group_Non-Demented
0,0,-0.147367,0.759418,0.137682,-0.785886,0,1,0,0,0,0,1,0,0,1,1
1,1,-2.176432,2.427471,1.709157,-1.956864,0,0,0,1,0,0,0,0,0,1,1
2,2,-0.254160,0.025475,-0.683238,-0.132040,0,0,0,1,0,0,1,0,0,1,0
3,3,-0.147367,-0.967943,-1.128881,0.949778,1,0,0,0,1,1,0,0,0,1,1
4,4,-2.496811,0.929930,2.107889,-0.922599,0,0,1,0,0,1,0,0,0,1,1

In [3]:
df = df.iloc[:, 1:]

df.head()

,Age,ASF,nWBV,eTIV,Gender_M,Educ_level_2.0,Educ_level_3.0,Educ_level_4.0,Educ_level_5.0,SES_level_2.0,SES_level_3.0,SES_level_4.0,SES_level_5.0,MMSE_Group_> 25,Group_Non-Demented
0,-0.147367,0.759418,0.137682,-0.785886,0,1,0,0,0,0,1,0,0,1,1
1,-2.176432,2.427471,1.709157,-1.956864,0,0,0,1,0,0,0,0,0,1,1
2,-0.254160,0.025475,-0.683238,-0.132040,0,0,0,1,0,0,1,0,0,1,0
3,-0.147367,-0.967943,-1.128881,0.949778,1,0,0,0,1,1,0,0,0,1,1
4,-2.496811,0.929930,2.107889,-0.922599,0,0,1,0,0,1,0,0,0,1,1

In [4]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [5]:
X.shape, y.shape

((608, 14), (608,))

In [7]:
AB_Tuned = AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         max_samples=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=100,
                                                         n_jobs=None,
                                                         oob_score=False,
                                                         random_state=10,
                                                         verbose=0,
                                                         warm_start=False),
                   learning_rate=0.1, n_estimators=1, random_state=10)

AB_Tuned.fit(X, y)

AdaBoostClassifier(base_estimator=RandomForestClassifier(random_state=10),
                   learning_rate=0.1, n_estimators=1, random_state=10)

## Saving the model to pickle file

In [14]:
pickle.dump(AB_Tuned, open("model.pkl", "wb"))

## Loading pickle file and testing the model prediction

In [16]:
model = pickle.load(open("model.pkl", "rb"))

In [51]:
val = model.predict([[-0.147367, 0.759418, 0.137682, -0.785886, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1]])

In [52]:
val[0]

1